[package]
name = "scylla_cdc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.12", features = ["full"] }
scylla = "0.2"
futures = "0.3.17"
hex = "0.4"
chrono = "0.4.19"
